name: Archive Repository

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Create archive directory
        run: mkdir -p archive

      - name: Copy repository contents to archive folder
        run: cp -r ./* archive/