name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up JDK (matching the version in the POM properties)
      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven

      # Step 3: Build the Parent Module
      - name: Build Parent Module
        run: mvn -B clean install -U

      # Step 4: Build All Submodules
      - name: Build All Submodules
        run: mvn -B verify
